# Comprehensive offline disease information for all 41 diseases in the Kaggle dataset.
# Used as fallback when the Gemini API is unavailable.

DISEASE_INFO = {
    "(vertigo) Paroymsal  Positional Vertigo": {
        "description": "Benign paroxysmal positional vertigo (BPPV) is a condition that causes brief episodes of dizziness triggered by changes in head position. It occurs when tiny calcium crystals in the inner ear become dislodged.",
        "commonSymptoms": ["vertigo", "nausea", "vomiting", "headache", "loss_of_balance"],
        "precautions": ["Avoid sudden head movements", "Sleep with head slightly elevated", "Perform Epley maneuver as directed", "Sit down immediately when dizzy"],
        "tests": ["Dix-Hallpike test", "Head-roll test", "Electronystagmography (ENG)", "MRI if symptoms persist"],
        "warningSigns": ["Sudden severe headache with vertigo", "Double vision or difficulty speaking", "Numbness or weakness on one side", "Vertigo lasting more than 24 hours continuously"],
    },
    "AIDS": {
        "description": "Acquired Immunodeficiency Syndrome (AIDS) is a chronic, potentially life-threatening condition caused by HIV. It damages the immune system, interfering with the body's ability to fight infections and disease.",
        "commonSymptoms": ["muscle_wasting", "patches_in_throat", "high_fever", "extra_marital_contacts"],
        "precautions": ["Take antiretroviral therapy (ART) as prescribed", "Practice safe sex", "Avoid sharing needles", "Regular medical checkups"],
        "tests": ["HIV antibody test (ELISA)", "HIV RNA/viral load test", "CD4 T-cell count", "Western blot confirmatory test"],
        "warningSigns": ["Rapid weight loss", "Recurring fever or night sweats", "Persistent diarrhea lasting more than a week", "Pneumonia or unusual infections"],
    },
    "Acne": {
        "description": "Acne is a skin condition that occurs when hair follicles become plugged with oil and dead skin cells. It causes whiteheads, blackheads, or pimples, and is most common among teenagers.",
        "commonSymptoms": ["skin_rash", "pus_filled_pimples", "blackheads", "scarring"],
        "precautions": ["Wash face twice daily with mild cleanser", "Avoid touching or picking at pimples", "Use non-comedogenic products", "Stay hydrated and eat a balanced diet"],
        "tests": ["Visual examination by dermatologist", "Hormonal panel if severe", "Bacterial culture if infected"],
        "warningSigns": ["Severe painful cystic acne", "Spreading infection with red streaks", "Acne not responding to treatment after 3 months", "Scarring or dark patches forming"],
    },
    "Alcoholic hepatitis": {
        "description": "Alcoholic hepatitis is liver inflammation caused by excessive alcohol consumption. It can range from mild to severe and life-threatening, and is a major risk factor for cirrhosis.",
        "commonSymptoms": ["vomiting", "yellowish_skin", "abdominal_pain", "swelling_of_stomach", "fluid_overload"],
        "precautions": ["Stop alcohol consumption completely", "Follow a nutritious diet", "Take prescribed medications", "Join a support group for alcohol cessation"],
        "tests": ["Liver function tests (LFTs)", "Complete blood count (CBC)", "Liver biopsy", "Abdominal ultrasound or CT scan"],
        "warningSigns": ["Severe jaundice (yellow skin/eyes)", "Vomiting blood or blood in stool", "Confusion or drowsiness (hepatic encephalopathy)", "Swollen abdomen with pain"],
    },
    "Allergy": {
        "description": "An allergy is an immune system response to a foreign substance that's not typically harmful to the body. These foreign substances are called allergens and can include certain foods, pollen, or pet dander.",
        "commonSymptoms": ["sneezing", "watering_from_eyes", "chills", "shivering"],
        "precautions": ["Avoid known allergens", "Take antihistamines as directed", "Carry epinephrine if prescribed", "Keep windows closed during high pollen seasons"],
        "tests": ["Skin prick test", "Specific IgE blood test", "Patch test for contact allergies", "Elimination diet for food allergies"],
        "warningSigns": ["Swelling of face, throat, or tongue", "Difficulty breathing or wheezing", "Rapid pulse or dizziness", "Loss of consciousness (anaphylaxis)"],
    },
    "Arthritis": {
        "description": "Arthritis is inflammation of one or more joints, causing pain and stiffness that can worsen with age. The most common types are osteoarthritis and rheumatoid arthritis.",
        "commonSymptoms": ["muscle_weakness", "stiff_neck", "swelling_joints", "movement_stiffness", "painful_walking"],
        "precautions": ["Regular gentle exercise like swimming", "Maintain a healthy weight", "Apply hot or cold compresses", "Take anti-inflammatory medications as prescribed"],
        "tests": ["X-ray of affected joints", "Blood tests (RF, anti-CCP, ESR, CRP)", "Joint fluid analysis", "MRI for detailed joint imaging"],
        "warningSigns": ["Sudden severe joint swelling", "Inability to move a joint", "Fever with joint inflammation", "Joint deformity developing"],
    },
    "Bronchial Asthma": {
        "description": "Bronchial asthma is a chronic respiratory condition where the airways become inflamed, narrow, and produce extra mucus, making breathing difficult. It can be triggered by allergens, exercise, or stress.",
        "commonSymptoms": ["fatigue", "cough", "high_fever", "breathlessness", "mucoid_sputum"],
        "precautions": ["Use inhaler as prescribed", "Avoid known triggers (smoke, dust, pollen)", "Monitor breathing with peak flow meter", "Create an asthma action plan with your doctor"],
        "tests": ["Spirometry (lung function test)", "Peak flow measurement", "Methacholine challenge test", "Chest X-ray"],
        "warningSigns": ["Severe breathlessness even at rest", "No improvement with rescue inhaler", "Bluish lips or fingernails", "Difficulty speaking due to breathlessness"],
    },
    "Cervical spondylosis": {
        "description": "Cervical spondylosis is age-related wear and tear affecting the spinal disks in the neck. It is very common and worsens with age, affecting more than 85% of people older than 60.",
        "commonSymptoms": ["back_pain", "weakness_in_limbs", "neck_pain", "dizziness", "loss_of_balance"],
        "precautions": ["Practice good posture", "Take regular breaks from desk work", "Do neck stretching exercises", "Use ergonomic pillow for sleeping"],
        "tests": ["X-ray of the cervical spine", "MRI scan", "CT scan", "Nerve conduction studies (EMG)"],
        "warningSigns": ["Loss of bladder or bowel control", "Progressive numbness in arms or legs", "Difficulty walking or loss of coordination", "Severe shooting pain down the arms"],
    },
    "Chicken pox": {
        "description": "Chickenpox is a highly contagious viral infection caused by the varicella-zoster virus. It causes an itchy, blister-like rash that first appears on the chest, back, and face, then spreads over the entire body.",
        "commonSymptoms": ["itching", "skin_rash", "fatigue", "lethargy", "high_fever"],
        "precautions": ["Isolate from others until all blisters crust over", "Keep nails trimmed to prevent scratching", "Apply calamine lotion for itch relief", "Stay hydrated and rest"],
        "tests": ["Visual diagnosis by doctor", "PCR test of blister fluid", "Blood test for varicella antibodies (IgM/IgG)"],
        "warningSigns": ["Rash spreading to eyes", "Fever above 102°F lasting more than 4 days", "Difficulty breathing", "Severe headache, stiff neck, or confusion"],
    },
    "Chronic cholestasis": {
        "description": "Chronic cholestasis is a condition where bile flow from the liver is reduced or blocked for a prolonged period. This leads to buildup of bile acids in the blood, causing itching, jaundice, and liver damage.",
        "commonSymptoms": ["itching", "vomiting", "yellowish_skin", "nausea", "loss_of_appetite"],
        "precautions": ["Follow a low-fat diet", "Take prescribed medications regularly", "Avoid alcohol completely", "Regular liver function monitoring"],
        "tests": ["Liver function tests (LFTs)", "Abdominal ultrasound", "MRCP (magnetic resonance cholangiopancreatography)", "Liver biopsy"],
        "warningSigns": ["Severe persistent jaundice", "Dark urine and pale stools", "Right upper abdominal pain", "Fever with chills suggesting infection"],
    },
    "Common Cold": {
        "description": "The common cold is a viral infection of the upper respiratory tract (nose and throat). It's usually harmless, though it might not feel that way. Many types of viruses can cause a common cold.",
        "commonSymptoms": ["continuous_sneezing", "chills", "fatigue", "cough", "high_fever"],
        "precautions": ["Rest and get plenty of sleep", "Stay hydrated", "Use over-the-counter cold remedies", "Wash hands frequently to prevent spreading"],
        "tests": ["Usually no tests needed", "Rapid strep test if sore throat is severe", "Chest X-ray if cough persists beyond 3 weeks"],
        "warningSigns": ["Fever above 103°F (39.4°C)", "Symptoms lasting more than 10 days", "Severe sinus pain or headache", "Shortness of breath or wheezing"],
    },
    "Dengue": {
        "description": "Dengue is a mosquito-borne viral infection causing flu-like illness. It is transmitted by Aedes mosquitoes and can develop into severe dengue (dengue hemorrhagic fever), which can be life-threatening.",
        "commonSymptoms": ["skin_rash", "chills", "joint_pain", "vomiting", "fatigue", "high_fever"],
        "precautions": ["Use mosquito repellent and nets", "Stay hydrated with ORS or fluids", "Take paracetamol for fever (avoid aspirin/ibuprofen)", "Eliminate standing water around your home"],
        "tests": ["NS1 antigen test (early detection)", "Dengue IgM/IgG antibody test", "Complete blood count (platelet count)", "Liver function tests"],
        "warningSigns": ["Severe abdominal pain", "Persistent vomiting", "Bleeding from gums or nose", "Rapid drop in platelet count"],
    },
    "Diabetes": {
        "description": "Diabetes is a chronic metabolic disease characterized by elevated blood sugar levels. Over time, uncontrolled diabetes can lead to serious damage to the heart, blood vessels, eyes, kidneys, and nerves.",
        "commonSymptoms": ["fatigue", "weight_loss", "excessive_hunger", "increased_appetite", "blurred_and_distorted_vision"],
        "precautions": ["Monitor blood sugar levels regularly", "Follow a balanced diet low in refined sugars", "Exercise regularly (at least 30 minutes/day)", "Take medications/insulin as prescribed"],
        "tests": ["Fasting blood glucose test", "HbA1c (glycated hemoglobin) test", "Oral glucose tolerance test (OGTT)", "Urine test for ketones"],
        "warningSigns": ["Blood sugar above 300 mg/dL", "Fruity-smelling breath (diabetic ketoacidosis)", "Extreme thirst with frequent urination", "Confusion or loss of consciousness"],
    },
    "Dimorphic hemmorhoids(piles)": {
        "description": "Hemorrhoids (piles) are swollen veins in the lower rectum and anus. They can be internal or external and are common, affecting millions of people. They often result from straining during bowel movements or increased pressure.",
        "commonSymptoms": ["constipation", "pain_during_bowel_movements", "pain_in_anal_region", "bloody_stool"],
        "precautions": ["Eat high-fiber diet", "Drink plenty of water", "Avoid straining during bowel movements", "Use sitz baths for relief"],
        "tests": ["Digital rectal examination", "Anoscopy", "Colonoscopy (if bleeding is significant)", "Complete blood count to check for anemia"],
        "warningSigns": ["Heavy rectal bleeding", "Severe pain that doesn't improve", "Prolapsed hemorrhoid that can't be pushed back", "Signs of anemia (dizziness, fatigue, pale skin)"],
    },
    "Drug Reaction": {
        "description": "A drug reaction is an adverse response to a medication. Reactions can range from mild skin rashes to severe, life-threatening conditions like anaphylaxis or Stevens-Johnson syndrome.",
        "commonSymptoms": ["itching", "skin_rash", "stomach_pain", "burning_micturition", "spotting_urination"],
        "precautions": ["Stop the suspected medication immediately", "Inform your doctor about the reaction", "Carry a list of drug allergies", "Wear a medical alert bracelet if severe"],
        "tests": ["Skin patch testing", "Blood tests for drug-specific antibodies", "Drug provocation test (in hospital setting)", "Liver and kidney function tests"],
        "warningSigns": ["Swelling of face, lips, or tongue", "Difficulty breathing", "Widespread blistering of skin", "High fever with skin peeling"],
    },
    "Fungal infection": {
        "description": "Fungal infections occur when fungi invade the body and the immune system cannot fight them off. They can affect the skin, nails, lungs, or other organs. Common types include ringworm, athlete's foot, and candidiasis.",
        "commonSymptoms": ["itching", "skin_rash", "nodal_skin_eruptions", "dischromic_patches"],
        "precautions": ["Keep affected areas clean and dry", "Wear loose-fitting clothing", "Don't share personal items (towels, combs)", "Complete the full course of antifungal medication"],
        "tests": ["KOH test (skin scraping)", "Fungal culture", "Wood's lamp examination", "Skin biopsy if needed"],
        "warningSigns": ["Rapidly spreading rash", "Fever with widespread skin lesions", "Pus or drainage from affected area", "Infection not improving after 2 weeks of treatment"],
    },
    "GERD": {
        "description": "Gastroesophageal reflux disease (GERD) occurs when stomach acid frequently flows back into the esophagus. This acid reflux can irritate the lining of the esophagus, causing heartburn and other symptoms.",
        "commonSymptoms": ["stomach_pain", "acidity", "ulcers_on_tongue", "vomiting", "chest_pain"],
        "precautions": ["Avoid spicy, fatty, and acidic foods", "Don't lie down within 3 hours of eating", "Elevate the head of your bed", "Eat smaller, more frequent meals"],
        "tests": ["Upper endoscopy (EGD)", "Esophageal pH monitoring", "Esophageal manometry", "Barium swallow X-ray"],
        "warningSigns": ["Difficulty swallowing that worsens", "Vomiting blood or black tarry stools", "Unexplained weight loss", "Persistent chest pain (rule out heart attack)"],
    },
    "Gastroenteritis": {
        "description": "Gastroenteritis is inflammation of the stomach and intestines, typically caused by viral or bacterial infection. It causes watery diarrhea, abdominal cramps, nausea, vomiting, and sometimes fever.",
        "commonSymptoms": ["vomiting", "diarrhoea", "dehydration", "abdominal_pain", "sunken_eyes"],
        "precautions": ["Drink plenty of fluids and oral rehydration salts", "Eat bland foods (BRAT diet)", "Rest", "Avoid dairy, caffeine, and fatty foods"],
        "tests": ["Stool culture", "Complete blood count (CBC)", "Basic metabolic panel for dehydration", "Stool ova and parasite exam"],
        "warningSigns": ["Blood in stool or vomit", "Inability to keep fluids down for 24 hours", "Fever above 104°F (40°C)", "Signs of dehydration (dark urine, dizziness, dry mouth)"],
    },
    "Heart attack": {
        "description": "A heart attack (myocardial infarction) occurs when blood flow to part of the heart muscle is blocked, usually by a blood clot. Without blood flow, the heart muscle begins to die. This is a medical emergency.",
        "commonSymptoms": ["chest_pain", "breathlessness", "vomiting", "sweating"],
        "precautions": ["Call emergency services immediately (911/112)", "Chew an aspirin if not allergic", "Rest in a comfortable position", "Do NOT drive yourself to the hospital"],
        "tests": ["ECG (Electrocardiogram)", "Troponin blood test", "Coronary angiography", "Echocardiogram"],
        "warningSigns": ["Crushing chest pain lasting more than 15 minutes", "Pain spreading to left arm, jaw, or back", "Cold sweats with nausea", "Sudden shortness of breath"],
    },
    "Hepatitis B": {
        "description": "Hepatitis B is a serious liver infection caused by the hepatitis B virus (HBV). It can become chronic and increase the risk of liver failure, liver cancer, or cirrhosis. A vaccine is available for prevention.",
        "commonSymptoms": ["itching", "fatigue", "lethargy", "yellowish_skin", "dark_urine", "loss_of_appetite"],
        "precautions": ["Get vaccinated", "Avoid sharing needles or razors", "Practice safe sex", "Take antiviral medications as prescribed"],
        "tests": ["HBsAg (Hepatitis B surface antigen)", "HBV DNA viral load", "Liver function tests", "Liver ultrasound or FibroScan"],
        "warningSigns": ["Severe jaundice", "Abdominal swelling (ascites)", "Confusion (hepatic encephalopathy)", "Vomiting blood"],
    },
    "Hepatitis C": {
        "description": "Hepatitis C is a viral infection that causes liver inflammation, sometimes leading to serious liver damage. It spreads through contaminated blood. Today, chronic hepatitis C is usually curable with oral medications.",
        "commonSymptoms": ["fatigue", "yellowish_skin", "nausea", "loss_of_appetite", "family_history"],
        "precautions": ["Avoid sharing needles or personal items", "Take prescribed antiviral medications", "Avoid alcohol", "Regular liver monitoring"],
        "tests": ["Anti-HCV antibody test", "HCV RNA PCR test", "Liver function tests", "FibroScan or liver biopsy"],
        "warningSigns": ["Severe jaundice with dark urine", "Abdominal swelling", "Easy bruising or bleeding", "Confusion or personality changes"],
    },
    "Hepatitis D": {
        "description": "Hepatitis D is a liver disease caused by the hepatitis D virus (HDV). It only occurs in people already infected with hepatitis B and can make hepatitis B more severe. It's the most severe form of viral hepatitis.",
        "commonSymptoms": ["joint_pain", "yellowish_skin", "dark_urine", "nausea", "vomiting", "fatigue"],
        "precautions": ["Get hepatitis B vaccination (prevents D too)", "Avoid sharing needles", "Practice safe sex", "Follow up regularly with a hepatologist"],
        "tests": ["Anti-HDV antibody test", "HDV RNA test", "HBsAg test", "Liver biopsy"],
        "warningSigns": ["Rapid worsening of jaundice", "Severe fatigue and confusion", "Abdominal swelling", "Bleeding problems"],
    },
    "Hepatitis E": {
        "description": "Hepatitis E is a liver disease caused by the hepatitis E virus (HEV). It's usually self-limiting but can be dangerous for pregnant women. It's most commonly spread through contaminated water.",
        "commonSymptoms": ["joint_pain", "vomiting", "fatigue", "high_fever", "yellowish_skin", "dark_urine"],
        "precautions": ["Drink only clean, purified water", "Practice good hand hygiene", "Avoid undercooked pork or shellfish", "Rest and stay hydrated"],
        "tests": ["Anti-HEV IgM antibody test", "HEV RNA PCR test", "Liver function tests", "Complete blood count"],
        "warningSigns": ["Severe jaundice in pregnant women", "Liver failure symptoms (confusion, bleeding)", "Persistent vomiting with dehydration", "Dark urine with pale stools for more than 2 weeks"],
    },
    "Hypertension": {
        "description": "Hypertension (high blood pressure) is a condition in which the force of blood against artery walls is too high. It's called the 'silent killer' because it often has no symptoms but can lead to serious health problems.",
        "commonSymptoms": ["headache", "chest_pain", "dizziness", "lack_of_concentration", "loss_of_balance"],
        "precautions": ["Reduce salt intake", "Exercise regularly (at least 150 min/week)", "Maintain a healthy weight", "Take blood pressure medications as prescribed"],
        "tests": ["Blood pressure measurement (multiple readings)", "Blood tests (cholesterol, kidney function)", "ECG (electrocardiogram)", "Echocardiogram"],
        "warningSigns": ["Blood pressure above 180/120 mmHg", "Severe headache with vision changes", "Chest pain or difficulty breathing", "Sudden numbness or weakness on one side"],
    },
    "Hyperthyroidism": {
        "description": "Hyperthyroidism occurs when the thyroid gland produces too much thyroid hormone. This speeds up the body's metabolism, causing unintentional weight loss, rapid heartbeat, and nervousness.",
        "commonSymptoms": ["weight_loss", "restlessness", "sweating", "fatigue", "mood_swings", "fast_heart_rate"],
        "precautions": ["Take anti-thyroid medication as prescribed", "Avoid iodine-rich foods if advised", "Get regular thyroid level checks", "Manage stress with relaxation techniques"],
        "tests": ["TSH blood test", "Free T3 and T4 tests", "Thyroid ultrasound", "Radioactive iodine uptake test"],
        "warningSigns": ["Rapid or irregular heartbeat", "Sudden weight loss with increased appetite", "Thyroid storm (fever, rapid pulse, delirium)", "Eye bulging or vision changes (Graves' disease)"],
    },
    "Hypoglycemia": {
        "description": "Hypoglycemia occurs when blood sugar (glucose) drops below normal levels (below 70 mg/dL). It's most common in people with diabetes but can occur in others. Immediate treatment is needed to restore blood sugar.",
        "commonSymptoms": ["vomiting", "fatigue", "anxiety", "sweating", "headache", "blurred_and_distorted_vision"],
        "precautions": ["Always carry fast-acting sugar (glucose tablets, juice)", "Eat regular meals and snacks", "Monitor blood sugar frequently", "Adjust medications with your doctor's guidance"],
        "tests": ["Blood glucose level test", "Fasting glucose test", "Insulin level test", "C-peptide test"],
        "warningSigns": ["Blood sugar below 54 mg/dL", "Confusion or unusual behavior", "Seizures", "Loss of consciousness"],
    },
    "Hypothyroidism": {
        "description": "Hypothyroidism occurs when the thyroid gland doesn't produce enough thyroid hormones. This slows metabolism, leading to fatigue, weight gain, and sensitivity to cold. It's more common in women over 60.",
        "commonSymptoms": ["fatigue", "weight_gain", "cold_hands_and_feets", "mood_swings", "lethargy", "dizziness"],
        "precautions": ["Take levothyroxine as prescribed", "Get regular thyroid level checks", "Maintain a balanced diet", "Exercise regularly to combat fatigue"],
        "tests": ["TSH blood test", "Free T4 test", "Thyroid antibody tests (anti-TPO)", "Lipid panel"],
        "warningSigns": ["Extreme fatigue or weakness", "Severe depression", "Myxedema (facial swelling, low body temperature)", "Slow heart rate with chest pain"],
    },
    "Impetigo": {
        "description": "Impetigo is a highly contagious bacterial skin infection that mainly affects infants and young children. It appears as red sores on the face, especially around the nose and mouth, which burst and form honey-colored crusts.",
        "commonSymptoms": ["skin_rash", "high_fever", "blister", "red_sore_around_nose", "yellow_crust_ooze"],
        "precautions": ["Keep the affected area clean", "Don't touch or scratch sores", "Wash hands frequently", "Don't share towels, clothes, or bedding"],
        "tests": ["Visual examination by doctor", "Bacterial culture of wound swab", "Blood tests if infection is spreading"],
        "warningSigns": ["Sores spreading rapidly", "Fever that doesn't respond to treatment", "Swollen lymph nodes", "Red streaks extending from sores"],
    },
    "Jaundice": {
        "description": "Jaundice is a condition in which the skin, whites of the eyes, and mucous membranes turn yellow because of high bilirubin levels. It's not a disease itself but a sign of an underlying condition affecting the liver or bile ducts.",
        "commonSymptoms": ["itching", "vomiting", "fatigue", "weight_loss", "high_fever", "yellowish_skin", "dark_urine"],
        "precautions": ["Stay well hydrated", "Eat a balanced diet", "Avoid alcohol", "Follow treatment for the underlying cause"],
        "tests": ["Bilirubin blood test (total and direct)", "Liver function tests (LFTs)", "Complete blood count (CBC)", "Abdominal ultrasound"],
        "warningSigns": ["Severe abdominal pain", "High fever with chills", "Confusion or drowsiness", "Dark urine with pale clay-colored stools"],
    },
    "Malaria": {
        "description": "Malaria is a life-threatening mosquito-borne disease caused by Plasmodium parasites. It causes high fever, chills, and flu-like symptoms. It's preventable and curable with timely treatment.",
        "commonSymptoms": ["chills", "vomiting", "high_fever", "sweating", "headache", "nausea", "muscle_pain"],
        "precautions": ["Use mosquito nets and repellent", "Take antimalarial prophylaxis when traveling", "Wear long sleeves and pants at dusk", "Eliminate standing water near your home"],
        "tests": ["Rapid Diagnostic Test (RDT)", "Blood smear microscopy (thick and thin)", "PCR for Plasmodium species", "Complete blood count"],
        "warningSigns": ["Temperature above 104°F (40°C)", "Severe headache with confusion", "Difficulty breathing", "Dark or bloody urine (blackwater fever)"],
    },
    "Migraine": {
        "description": "A migraine is a type of headache that can cause severe throbbing pain, usually on one side of the head. It's often accompanied by nausea, vomiting, and extreme sensitivity to light and sound.",
        "commonSymptoms": ["acidity", "headache", "blurred_and_distorted_vision", "excessive_hunger", "stiff_neck"],
        "precautions": ["Identify and avoid triggers", "Maintain regular sleep schedule", "Stay hydrated", "Take preventive medications if prescribed"],
        "tests": ["Neurological examination", "MRI of the brain", "CT scan if sudden onset", "Blood tests to rule out other causes"],
        "warningSigns": ["Worst headache of your life (thunderclap)", "Headache with fever and stiff neck", "Vision loss or double vision", "Headache after head injury"],
    },
    "Osteoarthristis": {
        "description": "Osteoarthritis is the most common form of arthritis, caused by wear and tear of joint cartilage over time. It most commonly affects joints in the hands, knees, hips, and spine.",
        "commonSymptoms": ["joint_pain", "neck_pain", "knee_pain", "hip_joint_pain", "swelling_joints"],
        "precautions": ["Maintain a healthy weight", "Exercise regularly with low-impact activities", "Apply hot or cold packs to affected joints", "Use assistive devices if needed"],
        "tests": ["X-ray of affected joints", "MRI for detailed assessment", "Joint fluid analysis", "Blood tests to rule out rheumatoid arthritis"],
        "warningSigns": ["Joint that becomes locked or gives way", "Sudden severe joint swelling", "Joint deformity", "Loss of joint function affecting daily activities"],
    },
    "Paralysis (brain hemorrhage)": {
        "description": "Brain hemorrhage (cerebral hemorrhage) is a type of stroke caused by bleeding in the brain. It can lead to paralysis, loss of speech, or death. Immediate medical attention is critical.",
        "commonSymptoms": ["vomiting", "headache", "weakness_of_one_body_side", "altered_sensorium"],
        "precautions": ["Call emergency services immediately", "Do NOT give food or water", "Note the time symptoms started (important for treatment)", "Keep the person still and comfortable"],
        "tests": ["CT scan of the brain (urgent)", "MRI of the brain", "Cerebral angiography", "Blood tests (clotting factors, blood count)"],
        "warningSigns": ["Sudden severe headache", "Sudden weakness or numbness on one side", "Sudden difficulty speaking or understanding", "Sudden loss of vision or balance"],
    },
    "Peptic ulcer diseae": {
        "description": "Peptic ulcer disease involves open sores that develop on the inside lining of the stomach (gastric ulcer) or the upper part of the small intestine (duodenal ulcer). The most common cause is H. pylori bacteria.",
        "commonSymptoms": ["vomiting", "loss_of_appetite", "abdominal_pain", "passage_of_gases", "internal_itching"],
        "precautions": ["Avoid NSAIDs (aspirin, ibuprofen)", "Quit smoking", "Limit alcohol and spicy foods", "Take prescribed proton pump inhibitors (PPIs)"],
        "tests": ["Upper endoscopy (EGD)", "H. pylori breath test", "H. pylori stool antigen test", "Blood test for H. pylori antibodies"],
        "warningSigns": ["Vomiting blood (red or coffee-ground)", "Black tarry stools (melena)", "Sudden severe abdominal pain", "Feeling faint or lightheaded"],
    },
    "Pneumonia": {
        "description": "Pneumonia is an infection that inflames the air sacs in one or both lungs. The air sacs may fill with fluid or pus, causing cough with phlegm, fever, chills, and difficulty breathing.",
        "commonSymptoms": ["chills", "fatigue", "cough", "high_fever", "breathlessness", "sweating", "chest_pain"],
        "precautions": ["Complete the full course of antibiotics", "Rest and drink plenty of fluids", "Use a humidifier", "Get pneumonia vaccine if recommended"],
        "tests": ["Chest X-ray", "Blood tests (CBC, blood cultures)", "Sputum culture", "Pulse oximetry"],
        "warningSigns": ["Difficulty breathing or rapid breathing", "Chest pain that worsens with breathing", "Coughing up blood", "High fever that doesn't respond to treatment"],
    },
    "Psoriasis": {
        "description": "Psoriasis is a chronic autoimmune condition that causes rapid skin cell buildup, resulting in scaling on the skin's surface. It causes patches of thick, red skin with silvery scales that can be itchy and painful.",
        "commonSymptoms": ["skin_rash", "joint_pain", "skin_peeling", "silver_like_dusting", "small_dents_in_nails"],
        "precautions": ["Moisturize skin regularly", "Avoid triggers (stress, cold weather, skin injuries)", "Use prescribed topical treatments", "Get moderate sunlight exposure"],
        "tests": ["Skin examination by dermatologist", "Skin biopsy", "Blood tests to rule out other conditions", "Joint X-rays if psoriatic arthritis suspected"],
        "warningSigns": ["Widespread rash covering large body areas", "Joint pain and swelling", "Pustular psoriasis (pus-filled blisters)", "Skin infection signs (warmth, swelling, pus)"],
    },
    "Tuberculosis": {
        "description": "Tuberculosis (TB) is a serious infectious disease that mainly affects the lungs. It's caused by Mycobacterium tuberculosis bacteria and spreads through the air when an infected person coughs or sneezes.",
        "commonSymptoms": ["chills", "vomiting", "fatigue", "weight_loss", "cough", "high_fever", "breathlessness", "sweating"],
        "precautions": ["Complete the full 6-9 month treatment course", "Cover mouth when coughing", "Ensure good ventilation in living spaces", "Isolate during the infectious period"],
        "tests": ["Tuberculin skin test (Mantoux/PPD)", "Chest X-ray", "Sputum AFB smear and culture", "GeneXpert/MTB-RIF test"],
        "warningSigns": ["Coughing up blood (hemoptysis)", "Severe weight loss", "Night sweats lasting more than 3 weeks", "Difficulty breathing"],
    },
    "Typhoid": {
        "description": "Typhoid fever is a bacterial infection caused by Salmonella typhi. It spreads through contaminated food and water. Without treatment, it can be life-threatening. It's common in areas with poor sanitation.",
        "commonSymptoms": ["chills", "vomiting", "fatigue", "high_fever", "headache", "belly_pain", "constipation"],
        "precautions": ["Drink only purified or boiled water", "Eat thoroughly cooked food", "Wash hands frequently", "Get typhoid vaccine before traveling to endemic areas"],
        "tests": ["Widal test", "Blood culture (gold standard)", "Typhidot test (IgM)", "Complete blood count"],
        "warningSigns": ["Sustained high fever above 104°F", "Severe abdominal pain or distension", "Intestinal bleeding (blood in stool)", "Confusion or delirium"],
    },
    "Urinary tract infection": {
        "description": "A urinary tract infection (UTI) is an infection in any part of the urinary system — kidneys, ureters, bladder, or urethra. Most UTIs involve the lower urinary tract (bladder and urethra) and are more common in women.",
        "commonSymptoms": ["burning_micturition", "bladder_discomfort", "foul_smell_of_urine", "continuous_feel_of_urine"],
        "precautions": ["Drink plenty of water", "Urinate frequently, don't hold it", "Wipe front to back", "Complete the full course of antibiotics"],
        "tests": ["Urinalysis", "Urine culture and sensitivity", "Complete blood count if fever present", "Kidney ultrasound if recurrent"],
        "warningSigns": ["Fever above 101°F with flank pain (kidney infection)", "Blood in urine", "Severe lower back pain", "Nausea and vomiting with urinary symptoms"],
    },
    "Varicose veins": {
        "description": "Varicose veins are enlarged, swollen, twisted veins that often appear blue or dark purple. They occur when faulty valves in the veins allow blood to flow in the wrong direction or pool. They most commonly affect the legs.",
        "commonSymptoms": ["fatigue", "cramps", "bruising", "obesity", "swollen_legs", "prominent_veins_on_calf"],
        "precautions": ["Elevate legs when resting", "Wear compression stockings", "Exercise regularly (walking, swimming)", "Avoid standing or sitting for long periods"],
        "tests": ["Duplex ultrasound", "Venography", "Physical examination", "CT scan for deep veins"],
        "warningSigns": ["Sudden leg swelling (could indicate blood clot)", "Skin ulcers near the ankle", "Bleeding from a varicose vein", "Hardened, painful, or discolored skin"],
    },
    "hepatitis A": {
        "description": "Hepatitis A is a highly contagious liver infection caused by the hepatitis A virus. It's usually spread through contaminated food or water. Unlike hepatitis B and C, it does not cause chronic liver disease and is rarely fatal.",
        "commonSymptoms": ["joint_pain", "vomiting", "yellowish_skin", "dark_urine", "nausea", "loss_of_appetite"],
        "precautions": ["Get hepatitis A vaccine", "Wash hands thoroughly after using the bathroom", "Drink only clean, purified water", "Avoid raw or undercooked shellfish"],
        "tests": ["Anti-HAV IgM antibody test", "Liver function tests (LFTs)", "Complete blood count", "Bilirubin levels"],
        "warningSigns": ["Severe jaundice lasting more than 6 months", "Sudden severe abdominal pain", "Persistent vomiting", "Signs of liver failure (confusion, bruising)"],
    },
}
