import Header from '../components/Header';
import Footer from '../components/Footer';

export default function About() {
  return (
    <div className="min-h-screen flex flex-col bg-[#F7F9FC]">
      <Header />
      
      <main className="flex-grow max-w-3xl mx-auto px-4 md:px-8 py-12 md:py-20 w-full">
        <h1 className="text-3xl md:text-4xl font-bold text-gray-900 mb-8">About SymptomSense</h1>
        
        <div className="bg-white rounded-2xl p-8 shadow-sm border border-gray-200 space-y-8">
          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-4">Project Context</h2>
            <div className="prose prose-blue text-gray-600">
              <p>
                SymptomSense is an educational prototype demonstrating the application of machine learning classification algorithms in the healthcare domain. It showcases how different models interpret the same high-dimensional binary input data (symptoms) to output probabilistic predictions (diseases).
              </p>
            </div>
          </section>
          
          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-4">Dataset Source</h2>
            <div className="prose prose-blue text-gray-600">
              <p>
                The models are trained on an open-source symptom-disease dataset commonly used for academic benchmarking. Due to the limited size of the dataset (for demo purposes), predictions may not encompass all possible medical conditions.
              </p>
            </div>
          </section>
          
          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-4">Tech Stack</h2>
            <div className="flex flex-wrap gap-2">
              <span className="px-3 py-1 bg-gray-100 border border-gray-200 rounded-lg text-sm font-medium text-gray-700">React 18</span>
              <span className="px-3 py-1 bg-gray-100 border border-gray-200 rounded-lg text-sm font-medium text-gray-700">Vite</span>
              <span className="px-3 py-1 bg-gray-100 border border-gray-200 rounded-lg text-sm font-medium text-gray-700">Tailwind CSS</span>
              <span className="px-3 py-1 bg-gray-100 border border-gray-200 rounded-lg text-sm font-medium text-gray-700">FastAPI</span>
              <span className="px-3 py-1 bg-gray-100 border border-gray-200 rounded-lg text-sm font-medium text-gray-700">Python 3</span>
              <span className="px-3 py-1 bg-gray-100 border border-gray-200 rounded-lg text-sm font-medium text-gray-700">Scikit-learn</span>
            </div>
          </section>
          
          <div className="p-4 bg-amber-50 rounded-xl border border-amber-200 mt-8">
            <h3 className="font-semibold text-amber-800 mb-2">Disclaimer</h3>
            <p className="text-sm text-amber-700">
              This application is designed strictly for educational and demonstration purposes. The predictions generated by the machine learning models are not a substitute for professional medical advice, diagnosis, or treatment. Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition.
            </p>
          </div>
        </div>
      </main>
      
      <Footer />
    </div>
  );
}
